blueprint:
  name: Motion-activated Light with Timer
  description: Turn on a light when motion is detected and turn it off when "no-motion" timer finishes.
  domain: automation
  source_url: https://github.com/DmitriySafronov/home-assistant_blueprints/blob/master/automation/motion_light_timer.yaml
  input:
    entity_trigger:
      name: Motion Sensor
      description: Binary sensor that detects motion
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    entity_target:
      name: Motion Light
      description: Light entity to control
      selector:
        entity:
          domain: light
    timer_no_motion:
      name: Wait timer
      description: Time to leave the light on after last motion is detected.
      selector:
        entity:
          domain: timer

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: !input timer_no_motion
    id: timer
  - platform: state
    entity_id:
      - !input entity_trigger
    id: motion
  - platform: state
    entity_id:
      - !input entity_target
    id: light

action:
  - choose:
      # Timer finished - turn off the motion light
      - conditions:
          - condition: trigger
            id: timer
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input entity_target
      
      # Motion detected while motion light is off - turn on motion light
      - conditions:
          - condition: trigger
            id: motion
          - condition: state
            entity_id: !input entity_trigger
            state: "on"
          - condition: state
            entity_id: !input entity_target
            state: "off"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input entity_target
      
      # Motion detected while motion light is on - cancel timer
      - conditions:
          - condition: trigger
            id: motion
          - condition: state
            entity_id: !input entity_trigger
            state: "on"
          - condition: state
            entity_id: !input entity_target
            state: "on"
        sequence:
          - service: timer.cancel
            target:
              entity_id: !input timer_no_motion
      
      # Motion stopped while motion light is on - start timer
      - conditions:
          - condition: trigger
            id: motion
          - condition: state
            entity_id: !input entity_trigger
            state: "off"
          - condition: state
            entity_id: !input entity_target
            state: "on"
        sequence:
          - service: timer.start
            target:
              entity_id: !input timer_no_motion
      
      # Motion light turned on externally - start timer
      - conditions:
          - condition: trigger
            id: light
          - condition: state
            entity_id: !input entity_target
            state: "on"
          - condition: template
            value_template: "{{ trigger.to_state.context.id != context.id }}"
        sequence:
          - service: timer.start
            target:
              entity_id: !input timer_no_motion
      
      # Motion light turned off externally - cancel timer
      - conditions:
          - condition: trigger
            id: light
          - condition: state
            entity_id: !input entity_target
            state: "off"
        sequence:
          - service: timer.cancel
            target:
              entity_id: !input timer_no_motion
