blueprint:
  name: Motion-activated Light with Timer and Condition & Illuminance
  description: Turn on a light when motion is detected and turn it off when "no-motion" timer finishes on specific condition and when ambient light is below threshold
  domain: automation
  source_url: https://github.com/disafronov/home-assistant_blueprints/blob/master/automation/motion_light_timer_condition_illuminance.yaml
  input:
    entity_trigger:
      name: Motion Sensor
      description: Binary sensor that detects motion
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    entity_illuminance:
      name: Illuminance Sensor
      description: Sensor that measures ambient light level
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    entity_illuminance_value:
      name: Illuminance Value
      description: Threshold value for ambient light level
      selector:
        entity:
          domain: input_number
    entity_condition:
      name: Condition
      description: Binary sensor or input boolean to enable/disable automation
      selector:
        entity:
          domain:
            - binary_sensor
            - input_boolean
    entity_target:
      name: Motion Light
      description: Light entity to control
      selector:
        entity:
          domain: light
    timer_no_motion:
      name: Wait timer
      description: Time to leave the light on after last motion is detected.
      selector:
        entity:
          domain: timer

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: !input timer_no_motion
    id: timer
  - platform: state
    entity_id:
      - !input entity_trigger
    id: motion
  - platform: state
    entity_id:
      - !input entity_target
    id: light

condition:
  - condition: state
    entity_id: !input entity_condition
    state: "on"

action:
  - choose:
      # Timer finished - turn off the motion light
      - conditions:
          - condition: trigger
            id: timer
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input entity_target
      
      # Motion detected + motion light is off + illuminance below threshold - turn on motion light
      - conditions:
          - condition: trigger
            id: motion
          - condition: state
            entity_id: !input entity_trigger
            state: "on"
          - condition: state
            entity_id: !input entity_target
            state: "off"
          - condition: numeric_state
            entity_id: !input entity_illuminance
            below: !input entity_illuminance_value
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input entity_target
      
      # Motion detected + motion light is on - cancel timer
      - conditions:
          - condition: trigger
            id: motion
          - condition: state
            entity_id: !input entity_trigger
            state: "on"
          - condition: state
            entity_id: !input entity_target
            state: "on"
        sequence:
          - service: timer.cancel
            target:
              entity_id: !input timer_no_motion
      
      # Motion stopped + motion light is on - start timer
      - conditions:
          - condition: trigger
            id: motion
          - condition: state
            entity_id: !input entity_trigger
            state: "off"
          - condition: state
            entity_id: !input entity_target
            state: "on"
        sequence:
          - service: timer.start
            target:
              entity_id: !input timer_no_motion
      
      # Motion light turned on externally - start timer
      - conditions:
          - condition: trigger
            id: light
          - condition: state
            entity_id: !input entity_target
            state: "on"
          - condition: template
            value_template: "{{ trigger.to_state.context.user_id is not none }}"
        sequence:
          - service: timer.start
            target:
              entity_id: !input timer_no_motion
      
      # Motion light turned off externally - cancel timer
      - conditions:
          - condition: trigger
            id: light
          - condition: state
            entity_id: !input entity_target
            state: "off"
        sequence:
          - service: timer.cancel
            target:
              entity_id: !input timer_no_motion
